image:
  repository: ghcr.io/example/k8s-pod-event-collector
  tag: v0.1.0
  pullPolicy: IfNotPresent

replicaCount: 1

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

env:
  clusterName: "ihx-ai-staging-mt-cluster"
  alertOnRestart: true
  alertOnCompletion: true
  alertOnEviction: true
  muteSeconds: 120
  ignoreExitCodeZero: true
